//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int model_id { get; set; }
        public Nullable<int> model_year { get; set; }
        public Nullable<double> horse_power { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
    
        public virtual member member { get; set; }
        public virtual model model { get; set; }
    }
}
