//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public club()
        {
            this.club_event = new HashSet<club_event>();
            this.member_club = new HashSet<member_club>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int founder { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
        public System.DateTime creation_date { get; set; }
    
        public virtual member member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<club_event> club_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member_club> member_club { get; set; }
    }
}
