//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_event
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int club_id { get; set; }
        public byte[] picture { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> route_start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string description { get; set; }
    
        public virtual club club { get; set; }
    }
}
