//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_club
    {
        public int member_id { get; set; }
        public int club_id { get; set; }
        public int role_type { get; set; }
        public System.DateTime join_date { get; set; }
    
        public virtual club club { get; set; }
        public virtual member member { get; set; }
        public virtual member_club_role member_club_role { get; set; }
    }
}
