//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_relation
    {
        public int member_id1 { get; set; }
        public int member_id2 { get; set; }
        public int state_id { get; set; }
    
        public virtual member member { get; set; }
        public virtual member member1 { get; set; }
        public virtual relation_state relation_state { get; set; }
    }
}
