//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int sender_id { get; set; }
        public int receiver_id { get; set; }
        public System.DateTime datetime { get; set; }
        public string content_message { get; set; }
        public int state_id { get; set; }
    
        public virtual member member { get; set; }
        public virtual member member1 { get; set; }
        public virtual message_state message_state { get; set; }
    }
}
