//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class revupEntities : DbContext
    {
        public revupEntities(string password)
: base(ReplacePassword(password))
        {
        }
        static string ReplacePassword(string password)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["revupEntities"].ConnectionString;

            connectionString = connectionString.Replace("{PASSWORD_PLACEHOLDER}", password);

            return connectionString;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<member_club> member_club { get; set; }
        public virtual DbSet<member_club_role> member_club_role { get; set; }
        public virtual DbSet<member_location> member_location { get; set; }
        public virtual DbSet<member_relation> member_relation { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<message_state> message_state { get; set; }
        public virtual DbSet<post_comment> post_comment { get; set; }
        public virtual DbSet<post_type> post_type { get; set; }
        public virtual DbSet<relation_state> relation_state { get; set; }
        public virtual DbSet<terrain_type> terrain_type { get; set; }
        public virtual DbSet<event_state> event_state { get; set; }
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<model> models { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<club> clubs { get; set; }
        public virtual DbSet<club_event> club_event { get; set; }
        public virtual DbSet<member> members { get; set; }
    }
}
