//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.post_comment = new HashSet<post_comment>();
            this.members = new HashSet<member>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int post_type { get; set; }
        public string description { get; set; }
        public System.DateTime post_date { get; set; }
        public string picture { get; set; }
        public long likes { get; set; }
        public string address { get; set; }
        public Nullable<int> route_id { get; set; }
        public int member_id { get; set; }
        public long comments { get; set; }
    
        public virtual post_type post_type1 { get; set; }
        public virtual route route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_comment> post_comment { get; set; }
        public virtual member member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> members { get; set; }
    }
}
