//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoriRevUp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_comment
    {
        public int id { get; set; }
        public int post_id { get; set; }
        public int member_id { get; set; }
        public string comment_content { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual member member { get; set; }
        public virtual post post { get; set; }
    }
}
